api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

v1_router = DefaultRouter()

v1_router.register(
    'subscriptions',
    views.SubscriptionsViewSet,
    basename='SubscriptionsAPI',
)
v1_router.register(
    'favorites',
    views.FavoritesViewSet,
    basename='FavoritesAPI',
)
v1_router.register(
    'purchases',
    views.PurchasesViewSet,
    basename='PurchasesAPI',
)


urlpatterns = [
    path('v1/', include(v1_router.urls)),
    path('v1/ingredients', views.IngredientsSearch.as_view(), name='ingredient_search'),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from recipes import views as recipes_views

handler404 = 'recipes.views.page_not_found'  # noqa
handler500 = 'recipes.views.server_error'  # noqa

urlpatterns = [
    path('404/', recipes_views.page_not_found),
    path('500/', recipes_views.server_error),
]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('api/', include('api.urls')),
    path('', include('recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('new_recipe/', views.new_recipe, name='new_recipe'),
    path('author/<str:username>/', views.AuthorList.as_view(), name='author'),
    path('favorite/', views.FavoriteList.as_view(), name='favorite'),
    path('recipe/<slug:slug>/', views.RecipeDetail.as_view(), name='recipe'),
    path('recipe/<slug:slug>/edit/', views.recipe_edit, name='recipe_edit'),
    path('recipe/<slug:slug>/delete/', views.recipe_delete, name='recipe_delete'),
    path('follow/', views.FollowList.as_view(), name='follow'),
    path('purchase/', views.PurchaseList.as_view(), name='purchase'),
    path('purchase/download', views.PurchaseListDownload, name='purchase_download'),
    path('purchase/<slug:slug>/delete/', views.purchase_delete, name='purchase_delete'),
]

recipes/forms.py
from django.forms import (CharField, CheckboxSelectMultiple,
                          ModelMultipleChoiceField, ValidationError, models)

from recipes.models import Ingredient, IngredientsInRecipe, Recipe, Tag


class RecipeForm(models.ModelForm):
    tags_in_recipe = ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=CheckboxSelectMultiple,
        required=True,
        label='Тэги',
    )
    ingredients_in_recipe = CharField(required=False)

    class Meta:
        model = Recipe
        fields = (
            'title',
            'image',
            'description',
            'tags_in_recipe',
            'time_to_cook',
        )

    def get_ingredients_ids(self):
        ingredients_ids = []
        for key in self.data:
            if 'Ingredient' in key:
                _, id = key.split('_')
                if id not in ingredients_ids:
                    ingredients_ids.append(id)
        return ingredients_ids

    def get_ingredients_list(self, ids, cleaned_data, unexist_ingredients):
        for i in ids:
            nameIngredient = 'nameIngredient_' + i
            valueIngredient = 'valueIngredient_' + i
            try:
                ingredient = Ingredient.objects.get(
                    title=self.data[nameIngredient]
                )
                cleaned_data['ingredients_in_recipe'][ingredient] = int(
                    self.data[valueIngredient]
                )
            except Ingredient.DoesNotExist:
                unexist_ingredients.append(self.data[nameIngredient])

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data['ingredients_in_recipe'] = {}
        unexist_ingredients = []
        ids = self.get_ingredients_ids()
        self.get_ingredients_list(ids, cleaned_data, unexist_ingredients)
        self.extraclean_ingredients_in_recipe(
            cleaned_data, unexist_ingredients
        )
        return cleaned_data

    def clean_slug(self):
        slug = self.cleaned_data['slug']
        if Recipe.objects.filter(slug=slug).exists():
            raise ValidationError(f'Адрес рецепта "{slug}" уже существует, '
                                  'назовите рецепт по-другому')
        return slug

    def clean_tags_in_recipe(self):
        tags_in_recipe = self.cleaned_data['tags_in_recipe']
        if not tags_in_recipe:
            raise ValidationError('Выберите хотя бы один тэг')
        return tags_in_recipe

    def extraclean_ingredients_in_recipe(self, cleaned_data, unexist_ingredients):
        ingredients_in_recipe = cleaned_data['ingredients_in_recipe']
        if not ingredients_in_recipe and not unexist_ingredients:
            self.add_error(
                'ingredients_in_recipe',
                'Нужно выбрать хотя бы один ингредиент'
            )
        if unexist_ingredients:
            error_msg = self.list_of_unexist_ingredients(unexist_ingredients)
            clean_ingredients = cleaned_data['ingredients_in_recipe']
            self.add_error('ingredients_in_recipe', f'{error_msg}')
            cleaned_data['ingredients_in_recipe'] = clean_ingredients
        return ingredients_in_recipe

    def save(self):
        instance = super().save()
        cleaned_data = self.cleaned_data
        instance.ingredients.all().delete()
        objs = [
            IngredientsInRecipe(
                recipe=self.instance,
                ingredient=k,
                quantity=v,
            )
            for k, v in cleaned_data['ingredients_in_recipe'].items()
        ]
        IngredientsInRecipe.objects.bulk_create(objs)
        return instance

    def list_of_unexist_ingredients(self, unexist_ingredients):
        if len(unexist_ingredients) == 1:
            return f'Ингредиента {unexist_ingredients[0]} нет в базе'
        list = ', '.join(unexist_ingredients)
        return f'Ингредиентов {list} нет в базе'

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Subquery, Sum
from django.shortcuts import HttpResponse, get_object_or_404, redirect, render
from django.template import loader
from django.views.generic import DetailView, ListView
from pytils.translit import slugify

from foodgram.settings import FOLLOWS_PAGINATE_BY, RECIPES_PAGINATE_BY
from users.models import User

from .forms import RecipeForm
from .models import IngredientsInRecipe, Purchase, Recipe
from .paginator import SafePaginator


class Index(ListView):
    """Выводит все рецепты."""
    model = Recipe
    paginate_by = RECIPES_PAGINATE_BY
    template_name = 'recipes/index.html'
    context_object_name = 'recipe'
    paginator_class = SafePaginator

    def get_queryset(self):
        return Recipe.objects.all_with_flags(
            self.request.user, self.request.tags
        )


class AuthorList(ListView):
    """Выводит все рецепты определённого автора."""
    paginate_by = RECIPES_PAGINATE_BY
    template_name = 'recipes/author.html'
    context_object_name = 'recipe'
    paginator_class = SafePaginator

    def get_queryset(self):
        self.author = get_object_or_404(User, username=self.kwargs['username'])
        return Recipe.objects.all_with_flags(
            self.request.user, self.request.tags, author=self.author
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        follow = (
            self.request.user.is_authenticated
            and self.request.user.authors.filter(author=self.author).exists()  # noqa
        )
        context['author'] = self.author
        context['follow'] = follow
        return context


class FavoriteList(LoginRequiredMixin, ListView):
    """Выводит все рецепты добавленные в избранное."""
    paginate_by = RECIPES_PAGINATE_BY
    template_name = 'recipes/favorite.html'
    context_object_name = 'recipe'
    paginator_class = SafePaginator

    def get_queryset(self):
        favorites = self.request.user.favorites.all()
        return Recipe.objects.all_with_flags(
            self.request.user, self.request.tags, favorites
        )


class RecipeDetail(DetailView):
    """Выводит один рецепт."""
    model = Recipe
    template_name = 'recipes/recipe_detail.html'
    context_object_name = 'recipe'

    def get_object(self):
        recipe = Recipe.objects.all_with_flags(
            self.request.user
        ).get(
            slug=self.kwargs['slug']
        )
        return recipe

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = context['recipe']
        follow = (
            self.request.user.is_authenticated
            and self.request.user.authors.filter(author=recipe.author).exists()  # noqa
        )
        context['follow'] = follow
        return context


class FollowList(LoginRequiredMixin, ListView):
    """Выводит всех авторов на которых подписан пользователь."""
    paginate_by = FOLLOWS_PAGINATE_BY
    template_name = 'recipes/follow.html'
    context_object_name = 'authors'
    paginator_class = SafePaginator

    def get_queryset(self):
        follows = self.request.user.authors.all()
        return User.objects.filter(pk__in=Subquery(follows.values('author')))


class PurchaseList(LoginRequiredMixin, ListView):
    """Выводит все рецепты которые добавлены в список покупок."""
    template_name = 'recipes/purchase.html'
    context_object_name = 'purchase'

    def get_queryset(self):
        return self.request.user.purchases.all().select_related('recipe')


def PurchaseListDownload(request):
    """Выводит список ингредиентов из списка покупок в txt файл."""
    response = HttpResponse(content_type='text/txt')
    response['Content-Disposition'] = 'attachment; filename="purchase_list.txt"'
    purchase_list = request.user.purchases.all()
    ingredients_list = IngredientsInRecipe.objects.filter(
        recipe__in=Subquery(purchase_list.values('recipe'))
    ).values(
        'ingredient__title', 'ingredient__dimension'
    ).annotate(
        total_quantity=Sum('quantity')
    )
    t = loader.get_template('recipes/recipe_list.txt')
    c = {'data': ingredients_list}
    response.write(t.render(c))
    return response


@ login_required
def new_recipe(request):
    """Создаёт новый рецепт."""
    form = RecipeForm(request.POST or None, files=request.FILES or None,)
    if form.is_valid():
        form.instance.author = request.user
        form.instance.slug = slugify(form.instance.title)[:50]
        form.save()
        return redirect(form.instance)

    return render(
        request,
        'recipes/new_recipe.html',
        {'form': form,
         }
    )


@ login_required
def recipe_edit(request, slug):
    """Редактирует рецепт."""
    recipe = get_object_or_404(Recipe, slug=slug)
    if recipe.author != request.user:
        return redirect(recipe.get_absolute_url())
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe,
    )
    if form.is_valid():
        form.instance.slug = slugify(form.instance.title)[:50]
        form.save()
        return redirect(form.instance)
    return render(
        request,
        'recipes/new_recipe.html',
        {'form': form,
         'recipe': recipe}
    )


@ login_required
def recipe_delete(request, slug):
    """Удаляет рецепт."""
    recipe = get_object_or_404(Recipe, slug=slug)
    if recipe.author != request.user:
        return redirect(recipe.get_absolute_url())
    recipe.delete()
    return redirect('recipes:index')


@ login_required
def purchase_delete(request, slug):
    """Удаляет рецепт из списка покупок."""
    purchase = get_object_or_404(
        Purchase,
        user=request.user,
        recipe__slug=slug,
    )
    purchase.delete()
    return redirect('recipes:purchase')


def page_not_found(request, exception):
    """Выводит страницу 404."""
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    """Выводит страницу 500."""
    return render(request, 'misc/500.html', status=500)

recipes/templates/recipes/author.html
{% extends 'base.html' %}
{% block title %}{% firstof author.get_full_name author.username %}{% endblock %}
{% load static %}
{% block content %}
{% if user.is_authenticated and request.user != author %}
{% include 'elements/button_subscribe.html' with cur_template='author' %}
{% endif %}
<div class="card-list">
    {% for recipe in recipe %}
    {% include "parts/recipe_card.html" %}
    {% endfor %}
</div>
{% endblock %}
{% block script %}
<script src="{% static 'recipes/js/components/MainCards.js' %}"></script>

<script src="{% static 'recipes/js/components/Purchases.js' %}"></script>
<script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
<script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>

<script src="{% static 'recipes/js/config/config.js' %}"></script>
<script src="{% static 'recipes/js/components/AuthorRecipe.js' %}"></script>
<script src="{% static 'recipes/js/components/Header.js' %}"></script>

<script src="{% static 'recipes/js/api/Api.js' %}"></script>
<script src="{% static 'recipes/authorRecipe.js' %}"></script>
{% endblock %}

recipes/templates/recipes/favorite.html
{% extends 'base.html' %}
{% block title %}Избранное{% endblock %}
{% load static %}
{% block content %}
<div class="card-list">
    {% for recipe in recipe %}
    {% include "parts/recipe_card.html" %}
    {% endfor %}
</div>
{% endblock %}
{% block script %}
<script src="{% static 'recipes/js/components/MainCards.js' %}"></script>

<script src="{% static 'recipes/js/components/Purchases.js' %}"></script>
<script src="{% static 'recipes/js/components/Favorites.js' %}"></script>

<script src="{% static 'recipes/js/config/config.js' %}"></script>
<script src="{% static 'recipes/js/components/CardList.js' %}"></script>
<script src="{% static 'recipes/js/components/Header.js' %}"></script>

<script src="{% static 'recipes/js/api/Api.js' %}"></script>
<script src="{% static 'recipes/favorite.js' %}"></script>
{% endblock %}

recipes/templates/recipes/follow.html
{% extends 'base.html' %}
{% block title %}Мои подписки{% endblock %}
{% load static %}
{% block headcss %}<link rel="stylesheet" href="{% static 'recipes/pages/myFollow.css' %}">{% endblock %}
{% block content %}
<div class="card-list">
    {% for author in authors %}
        {% include "parts/follow_card.html" with recipes=author.recipes.all %}
    {% endfor %}
</div>
{% endblock %}
{% block script %}
<script src="{% static 'recipes/js/config/config.js' %}"></script>
<script src="{% static 'recipes/js/components/MainCards.js' %}"></script>
<script src="{% static 'recipes/js/components/MyFollow.js' %}"></script>
<script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>
<script src="{% static 'recipes/js/components/Header.js' %}"></script>
<script src="{% static 'recipes/js/api/Api.js' %}"></script>
<script src="{% static 'recipes/myFollow.js' %}"></script>
{% endblock %}

recipes/templates/recipes/index.html
{% extends 'base.html' %}
{% block title %}Рецепты{% endblock %}
{% block content %}
<div class="card-list">
    {% for recipe in recipe %}
    {% include "parts/recipe_card.html" with recipe=recipe %}
    {% endfor %}
</div>
{% endblock %}
{% block script %}
{% load static %}
<script src="{% static 'recipes/js/components/MainCards.js' %}"></script>

<script src="{% static 'recipes/js/components/Purchases.js' %}"></script>

{% if user.is_authenticated %}
<script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
{% endif %}

<script src="{% static 'recipes/js/config/config.js' %}"></script>
<script src="{% static 'recipes/js/components/CardList.js' %}"></script>
<script src="{% static 'recipes/js/components/Header.js' %}"></script>

<script src="{% static 'recipes/js/api/Api.js' %}"></script>
{% if user.is_authenticated %}
<script src="{% static 'recipes/indexAuth.js' %}"></script>
{% else %}
<script src="{% static 'recipes/indexNotAuth.js' %}"></script>
{% endif %}
{% endblock %}

recipes/templates/recipes/new_recipe.html
{% extends 'base.html' %}
{% block title %}{{ form.instance.title|yesno:"Редактирование рецепта,Создание рецепта" }}{% endblock%}
{% load static %}
{% load custom_filters %}
{% block headcss %}
<link rel="stylesheet" href="{% static 'recipes/pages/form.css' %}">{% endblock %}
{% block content %}
<div class="form-container">
    <form class="form" method="post"
        action="{% if form.instance == recipe %}{% url 'recipes:recipe_edit' recipe.slug %}{% else %}{% url 'recipes:new_recipe' %}{% endif %}"
        enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'blocks/form_group.html' with field=form.title css='form__input' %}
        {% include 'parts/form_tags.html' with instance_tags=form.instance.list_of_tags form_tags=form.cleaned_data.tags_in_recipe %}
        {% include 'parts/form_ingredients.html' with field=form.ingredients_in_recipe %}
        {% include 'blocks/form_group.html' with field=form.time_to_cook label='минут' time=True css='form__input' %}
        {% include 'blocks/form_group.html' with field=form.description css='form__textarea' %}
        {% include 'blocks/form_group.html' with field=form.image %}
        {% if form.instance == recipe %}
        {% url 'recipes:recipe_delete' recipe.slug as recipe_delete_url %}
        {% include 'elements/button_style_blue_form.html' with text='Сохранить' url=recipe_delete_url url_text='Удалить' %}
        {% else %}
        {% include 'elements/button_style_blue_form.html' with text='Создать рецепт' %}
        {% endif %}
    </form>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'recipes/js/config/config.js' %}"></script>
<script src="{% static 'recipes/js/components/Header.js' %}"></script>
<script src="{% static 'recipes/js/utils/debouncing.js' %}"></script>
<script src="{% static 'recipes/js/api/Api.js' %}"></script>
<script src="{% static 'recipes/formRecipe.js' %}"></script>
{% endblock %}

recipes/templates/recipes/purchase.html
{% extends 'base.html' %}
{% block title %}Список покупок{% endblock %}
{% load static %}
{% block headcss %}
<link rel="stylesheet" href="{% static 'recipes/pages/shopList.css' %}">{% endblock %}
{% block content %}
<div class="card-list card-list_column">
    <ul class="shopping-list">
        {% for purchase in purchase %}
        {% include 'parts/shopping_list_item.html' %}
        {% endfor %}
    </ul>
    {% url 'recipes:purchase_download' as purchase_download_url %}
    {% include 'elements/button_style_blue_link.html' with text='Скачать список' url=purchase_download_url %}
</div>
{% endblock %}
{% block script %}
<script src="{% static 'recipes/js/config/config.js' %}"></script>
<script src="{% static 'recipes/js/components/Header.js' %}"></script>
<script src="{% static 'recipes/js/components/ShopList.js' %}"></script>
<script src="{% static 'recipes/js/api/Api.js' %}"></script>
<script src="{% static 'recipes/shopList.js' %}"></script>
{% endblock %}

recipes/templates/recipes/recipe_detail.html
{% extends 'base.html' %}
{% block title %}{{ recipe.title }}{% endblock %}
{% load static %}
{% load custom_filters %}
{% block headcss %}<link rel="stylesheet" href="{% static 'recipes/pages/single.css' %}">{% endblock %}
{% block content %}
{% include 'parts/single_card.html' %}
{% endblock %}

{% block script %}
<script src="{% static 'recipes/js/components/Purchases.js' %}"></script>
<script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
<script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>
<script src="{% static 'recipes/js/config/config.js' %}"></script>

<script src="{% static 'recipes/js/components/MainCards.js' %}"></script>
<script src="{% static 'recipes/js/components/SingleCard.js' %}"></script>
<script src="{% static 'recipes/js/components/Header.js' %}"></script>

<script src="{% static 'recipes/js/api/Api.js' %}"></script>
<script src="{% static 'recipes/singlePage.js' %}"></script>
{% endblock %}