api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

v1_router = DefaultRouter()

v1_router.register(
    'subscriptions',
    views.SubscriptionsViewSet,
    basename='SubscriptionsAPI',
)
v1_router.register(
    'favorites',
    views.FavoritesViewSet,
    basename='FavoritesAPI',
)
v1_router.register(
    'purchases',
    views.PurchasesViewSet,
    basename='PurchasesAPI',
)


urlpatterns = [
    path('v1/', include(v1_router.urls)),
    path('v1/ingredients', views.IngredientsSearch.as_view(), name='ingredient_search'),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from recipes import views as recipes_views

handler404 = 'recipes.views.page_not_found'  # noqa
handler500 = 'recipes.views.server_error'  # noqa

urlpatterns = [
    path('404/', recipes_views.page_not_found),
    path('500/', recipes_views.server_error),
]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('api/', include('api.urls')),
    path('', include('recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('new_recipe/', views.new_recipe, name='new_recipe'),
    path('author/<str:username>/', views.AuthorList.as_view(), name='author'),
    path('favorite/', views.FavoriteList.as_view(), name='favorite'),
    path('recipe/<slug:slug>/', views.RecipeDetail.as_view(), name='recipe'),
    path('recipe/<slug:slug>/edit/', views.recipe_edit, name='recipe_edit'),
    path('recipe/<slug:slug>/delete/', views.recipe_delete, name='recipe_delete'),
    path('follow/', views.FollowList.as_view(), name='follow'),
    path('purchase/', views.PurchaseList.as_view(), name='purchase'),
    path('purchase/download', views.PurchaseListDownload, name='purchase_download'),
    path('purchase/<slug:slug>/delete/', views.purchase_delete, name='purchase_delete'),
]

templates/elements/button_favorite.html
{% load custom_filters %}
{% if cur_template == 'single_card_info' %}
    {% if recipe.is_favorite %}
    <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_big icon-favorite_active"></span></button>
    <div class="single-card__favorite-tooltip tooltip">Убрать из избранного</div>
    {% else %}
    <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite_big"></span></button>
    <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
    {% endif %}
{% elif cur_template == 'card_footer' %}
    {% if recipe.is_favorite %}
    <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
    {% else %}
    <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
    {% endif %}
{% endif %}

templates/elements/button_purchase.html
{% load custom_filters %}
{% if cur_template == 'single_card_info' %}
    {% if recipe.is_purchase %}
    <li class="single-card__item"><button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check"></span>Рецепт добавлен</button></li>
    {% else %}
    <li class="single-card__item"><button class="button button_style_blue" name="purchases" data-out><span class="icon-plus"></span>Добавить в покупки</button></li>
    {% endif %}
{% elif cur_template == 'card_footer' %}
    {% if recipe.is_purchase %}
    <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span>Рецепт добавлен</button>
    {% else %}
    <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
    {% endif %}
{% endif %}

templates/elements/button_style_blue_form.html
<div class="form__footer">
    <button class="button button_style_blue">{{ text }}</button>
    {% if url %}
    <a style="margin-left: 2.5em" class="form__ingredient-link" href='{{ url }}'>{{ url_text }}</a>
    {% endif %}
</div>

templates/elements/button_style_blue_link.html
<a href="{{ url }}"><button class="button button_style_blue">{{ text }}</button></a>

templates/elements/card_title.html
<a class="card__title link" href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a>

templates/elements/form_field_item_ingredient.html
{% if form.errors %}
    {% for key, value in form.cleaned_data.ingredients_in_recipe.items %}
    <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
        <span> {{ key.title }} {{ value }} {{ key.demension }}</span>
        <span class="form__field-item-delete"></span>
        <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ key.title }}">
        <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ value }}">
        <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ key.dimension }}">
    </div>
    {% endfor %}
{% else %}
    {% for ingredient in recipe.ingredients.all %}
    <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
        <span> {{ ingredient.ingredient }} {{ ingredient.quantity }} {{ ingredient.ingredient.dimension }}</span>
        <span class="form__field-item-delete"></span>
        <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.ingredient }}">
        <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.quantity }}">
        <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingredient.ingredient.dimension }}">
    </div>
    {% endfor %}
{% endif %}

templates/elements/main_header.html
<div class="main__header">
    <h1 class="main__title">{{ text }}</h1>
</div>

templates/elements/main_title.html
<h1 class="main__title">
    {% if current_url == 'recipes:index' %} 
    Рецепты 
    {% elif current_url == 'recipes:author' %} 
    {% firstof author.get_full_name author.username %}
    {% elif current_url == 'recipes:favorite' %} 
    Избранное 
    {% elif current_url == 'recipes:follow' %} 
    Мои подписки 
    {% elif current_url == 'recipes:purchase' %} 
    Мои покупки
    {% elif current_url == 'recipes:new_recipe' %} 
    Создание рецепта
    {% elif current_url == 'recipes:recipe_edit' %} 
    Редактирование рецепта
    {% endif %}
</h1>

templates/elements/recipe_title.html
<h3 class="recipe__title"><a class="recipe__title link" href="{{ purchase.recipe.get_absolute_url }}">{{ purchase.recipe.title }}</a></h3>

templates/elements/shopping_list_delete_button.html
<a href="{% url 'recipes:purchase_delete' purchase.recipe.slug %}" class="shopping-list__button link">Удалить</a>

templates/elements/single_card_link.html
<li class="single-card__item">  <a style="margin-left: 2.5em" href="{{ url }}" class="single-card__text">{{ text }}</a></li>

templates/elements/single_card_section_title.html
<h3 class="single-card__section-title">{{ text }}</h3>

templates/elements/single_card_title.html
<h1 class="single-card__title">{{ recipe.title }}</h1>

templates/elements/tag_badge.html
<li class="single-card__item"><span class="badge badge_style_{{ tag.tag.color }}">{{ tag.tag.title }}</span></li>