about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

v1_router = DefaultRouter()

v1_router.register(
    'subscriptions',
    views.SubscriptionsViewSet,
    basename='SubscriptionsAPI',
)
v1_router.register(
    'favorites',
    views.FavoritesViewSet,
    basename='FavoritesAPI',
)
v1_router.register(
    'purchases',
    views.PurchasesViewSet,
    basename='PurchasesAPI',
)


urlpatterns = [
    path('v1/', include(v1_router.urls)),
    path('v1/ingredients', views.IngredientsSearch.as_view(), name='ingredient_search'),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from recipes import views as recipes_views

handler404 = 'recipes.views.page_not_found'  # noqa
handler500 = 'recipes.views.server_error'  # noqa

urlpatterns = [
    path('404/', recipes_views.page_not_found),
    path('500/', recipes_views.server_error),
]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('api/', include('api.urls')),
    path('', include('recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('new_recipe/', views.new_recipe, name='new_recipe'),
    path('author/<str:username>/', views.AuthorList.as_view(), name='author'),
    path('favorite/', views.FavoriteList.as_view(), name='favorite'),
    path('recipe/<slug:slug>/', views.RecipeDetail.as_view(), name='recipe'),
    path('recipe/<slug:slug>/edit/', views.recipe_edit, name='recipe_edit'),
    path('recipe/<slug:slug>/delete/', views.recipe_delete, name='recipe_delete'),
    path('follow/', views.FollowList.as_view(), name='follow'),
    path('purchase/', views.PurchaseList.as_view(), name='purchase'),
    path('purchase/download', views.PurchaseListDownload, name='purchase_download'),
    path('purchase/<slug:slug>/delete/', views.purchase_delete, name='purchase_delete'),
]

users/urls.py
from django.urls import include, path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', include('django.contrib.auth.urls')),
]

templates/parts/follow_card.html
<div class="card-user" data-author="{{ author.id }}">
    <div class="card-user__header">
        <a class="card-user__title link" href="{% url 'recipes:author' author.username %}"> {% firstof author.get_full_name author.username %} </a>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% for recipe in recipes|slice:":3" %}
            <li class="card-user__item">
                <div class="recipe">
                    <img src="{% if recipe.image %} {{ recipe.image.url }} {% else %} {% load static %} {% static 'recipes/nophoto.png' %} {% endif %}"
                        alt="{{ recipe.title }}" class="recipe__image">
                    <a class="recipe__title link" href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a>
                    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time_to_cook }} мин.</p>
                </div>
            </li>
            {% endfor %}
            {% if recipes.count > 3 %}
            <li class="card-user__item">
                {% load custom_filters %}
                {% with count=recipes.count|add:"-3" %}
                <a href="{% url 'recipes:author' author.username %}" class="card-user__link link">Еще {{ count }} {{ count|ru_pluralize:"рецепт,рецепта,рецептов" }}...</a>
                {% endwith %}
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="card-user__footer">
        {% csrf_token %}
        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
    </div>
</div>

templates/parts/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'recipes:index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/parts/form_container_with_form.html
<div class="form-container">
    <form class="form" action="{% url 'recipes:signup" %}" method="POST">
        {% block form_content %}
        {% endblock %}
    </form>
</div>

templates/parts/form_ingredients.html
<div class="form__group">
    <label for="nameIngredient" class="form__label">Ингредиенты</label>
    <div class="form__field-group">
        <div class="form__field-group-ingredientes">
            <div class="form__dropdown">
                <input type="text" id="nameIngredient" class="form__input">
                <div class="form__dropdown-items"></div>
            </div>
            <input type="number" id="cantidad" class="form__input" min="0">
            <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
        </div>
        {% include "blocks/form_block_ingredients.html" with field=form.ingredients_in_recipe %}
        <span class="form__error">{{ field.errors }}</span>
    </div>
</div>

templates/parts/form_tags.html
<div class="form__group">
    <p class="form__label">{{ form.tags_in_recipe.label }}</p>
    <div class="form__field-group">
        <div class="tags">
            {% for tag in form.tags_in_recipe %}
                {% include "blocks/tags_form.html" %}
            {% endfor %}
        </div>
        <span class="form__error">{{ form.tags_in_recipe.errors }}</span>
    </div>
</div>

templates/parts/menu.html
<header class="header"></header>
<nav class="nav">
    <div class="nav__container container">
        <ul class="nav__items list">
            {% url "recipes:index" as index_url %}
            {% include "elements/nav_item.html" with text="Рецепты" url=index_url %}
            {% if user.is_authenticated %}
            {% url "recipes:follow" as follow_url %}
            {% include "elements/nav_item.html" with text="Мои подписки" url=follow_url %}
            {% url "recipes:new_recipe" as new_recipe_url %}
            {% include "elements/nav_item.html" with text="Создать рецепт" url=new_recipe_url %}
            {% url "recipes:favorite" as favorite_url %}
            {% include "elements/nav_item.html" with text="Избранное" url=favorite_url %}
            {% endif %}
            {% url "recipes:purchase" as purchase_url %}
            {% include "elements/nav_item_purchase.html" with text="Список покупок" url=purchase_url %}
        </ul>
        <ul class="nav__items list">
            {% if user.is_authenticated %}
            {% url "users:password_change" as password_change_url %}
            {% include "elements/nav_item.html" with text="Изменить пароль" url=password_change_url %}
            {% url "users:logout" as logout_url %}
            {% include "elements/nav_item.html" with text="Выход" url=logout_url %}
            {% else %}
            {% url "users:login" as login_url %}
            {% include "elements/nav_item.html" with text="Войти" url=login_url %}
            {% url "users:signup" as signup_url %}
            {% include "elements/nav_item.html" with text="Создать аккаунт" url=signup_url %}
            {% endif %}
        </ul>
    </div>
</nav>
</header>

templates/parts/nav.html
<div class="main__header">
    {% include "elements/main_title.html" %}
    {% if current_url == "recipes:index" or current_url == "recipes:author" or current_url == "recipes:favorite" %}
    {% include "blocks/tags.html" %}
    {% endif %}
</div>

templates/parts/paginator.html
{% if page_obj.has_other_pages %}
{% load custom_filters %}
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if page_obj.has_previous %}
        <li class="pagination__item"><a class="pagination__link link" href="?{% query_transform page=page_obj.previous_page_number %}"><span class="icon-left"></span></a></li>
        {% else %}
        <li class="pagination__item"><a class="pagination__link link"><span class="icon-left"></span></a></li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link" href="?{% query_transform page=i %}">{{ i }}</a></li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?{% query_transform page=i %}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="pagination__item"><a class="pagination__link link" href="?{% query_transform page=page_obj.next_page_number %}"><span class="icon-right"></span></a></li>
        {% else %}
        <li class="pagination__item"><a class="pagination__link link"><span class="icon-right"></span></a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

templates/parts/recipe_card.html
<div class="card" data-id="{{ recipe.id }}">
    {% include "elements/card_image.html" with css="card__image" %}
    {% include "blocks/card_body.html" %}
    {% include "blocks/card_footer.html" %}
</div>

templates/parts/shopping_list_item.html
{% load static %}
<li class="shopping-list__item">
    <div class="recipe recipe_reverse">
        {% include "elements/card_image.html" with recipe=purchase.recipe css="recipe__image recipe__image_big" %}
        {% include "elements/recipe_title.html" with cur_template="shopping_list_item" %}
        {% include "elements/icon_time.html" with css="recipe__text" recipe=purchase.recipe %}
    </div>
    {% include "elements/shopping_list_delete_button.html" %}
</li>

templates/parts/single_card.html
<div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
    {% csrf_token %}
    {% include "elements/card_image.html" with css="single-card__image" %}
    {% include "blocks/single_card_info.html" %}
</div>